# Configuration pour le déploiement sur Netlify

[build]
  # Le dossier contenant les fichiers du site (index.html, etc.)
  # Comme nos fichiers sont à la racine, nous laissons tel quel.
  publish = "."

[functions]
  # Le dossier contenant nos fonctions serverless (api/auth.js)
  directory = "api"
